# Generated by Django 4.2.7 on 2024-02-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icp_api', '0004_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
