# Generated by Django 4.2.7 on 2024-03-04 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icp_api', '0006_alter_apiuser_first_name_alter_apiuser_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('poster_id', models.AutoField(primary_key=True, serialize=False)),
                ('poster_path', models.CharField(max_length=255)),
                ('movie_id', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, to='icp_api.film')),
                ('tmdb_id', models.ForeignKey(db_column='tmdb_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='icp_api.links')),
            ],
            options={
                'db_table': 'posters',
            },
        ),
    ]
