# Generated by Django 4.2.7 on 2024-03-04 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icp_api', '0007_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='movie_id',
        ),
    ]
