# Generated by Django 4.2.7 on 2024-03-04 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icp_api', '0008_remove_poster_movie_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMDb',
            fields=[
                ('tmdb_id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_id', models.ForeignKey(db_column='movie_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='icp_api.film')),
            ],
            options={
                'db_table': 'tmdb',
            },
        ),
        migrations.AlterField(
            model_name='poster',
            name='tmdb_id',
            field=models.ForeignKey(db_column='tmdb_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='icp_api.tmdb'),
        ),
    ]
