# Generated by Django 4.2.7 on 2024-03-04 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icp_api', '0011_alter_poster_tmdb_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poster',
            new_name='TMDbPoster',
        ),
        migrations.AlterModelTable(
            name='tmdbposter',
            table='tmdb_posters',
        ),
        migrations.DeleteModel(
            name='Links',
        ),
    ]
