# Generated by Django 4.2.7 on 2024-03-05 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icp_api', '0012_rename_poster_tmdbposter_alter_tmdbposter_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(db_column='movie_id', primary_key=True, serialize=False)),
                ('movie_title', models.CharField(db_column='movie_title', max_length=200)),
                ('movie_genres', models.CharField(db_column='movie_genres', max_length=100)),
                ('release_year', models.IntegerField(db_column='release_year')),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icp_api.movie'),
        ),
        migrations.AlterField(
            model_name='tmdb',
            name='movie_id',
            field=models.ForeignKey(db_column='movie_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='icp_api.movie'),
        ),
        migrations.DeleteModel(
            name='Film',
        ),
    ]
