# Generated by Django 4.2.7 on 2024-03-24 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('icp_api', '0013_movie_alter_rating_movie_alter_tmdb_movie_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='created_at',
            field=models.BigIntegerField(),
        ),
    ]
