# Generated by Django 4.2.7 on 2024-03-25 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icp_api', '0015_remove_rating_updated_at_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
