# Generated by Django 4.2.7 on 2024-03-27 22:56

from django.db import migrations
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('icp_api', '0016_alter_tag_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='created_at',
            field=django_unixdatetimefield.fields.UnixDateTimeField(),
        ),
    ]
