# Generated by Django 4.2.7 on 2024-03-27 22:58

from django.db import migrations
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('icp_api', '0017_alter_rating_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='created_at',
            field=django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True),
        ),
    ]
