# Generated by Django 4.2.7 on 2024-03-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icp_api', '0018_alter_rating_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSlug',
            fields=[
                ('slug_id', models.AutoField(db_column='slug_id', primary_key=True, serialize=False)),
                ('movie_id', models.ForeignKey(db_column='movie_id', on_delete=models.CASCADE, to='icp_api.Movie')),
                ('movie_slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'movie_slugs',
            },
        ),
    ]
