# Generated by Django 4.2.7 on 2024-03-28 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icp_api', '0019_movieslug'),
    ]

    operations = [
    ]
