# Generated by Django 4.2.7 on 2024-03-28 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icp_api', '0021_auto_20240328_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieslug',
            name='movie_id',
            field=models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, to='icp_api.movie', unique=True),
        ),
    ]
