# Generated by Django 4.2.7 on 2024-03-28 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icp_api', '0022_alter_movieslug_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieslug',
            name='movie_id',
            field=models.OneToOneField(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, to='icp_api.movie'),
        ),
    ]
